server:
  port: 8080
spring:
  datasource:
    url: jdbc:${DATASOURCE_DB:mysql}://${DATASOURCE_HOST:123.207.202.166}:${DATASOURCE_PORT:3306}/yoga?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:YPlus_Root@2019}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.jdbc.Driver}

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true