eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
spring:
  application:
    name: user-servie
  datasource:
    username: root
    password: YPlus_Root@2019
    url: jdbc:mysql://123.207.202.166:3306/yoga?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
    #实体类所在包
  type-aliases-package: com.yplus.user.entity