server:
  port: 8088

spring:
  thymeleaf:
    encoding: UTF-8
    cache: false

  datasource:
    username: root
    password: Tjk020900*
    url: jdbc:mysql://116.62.50.224:3306/demo5?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml